### ISSUE TITLE
Scroll bar hidden behind header

### ISSUE THREAD

**Issue by daviddob** [thomasmmitchell/doomsday#11]
When you have enough certs that there is a scroll bar, scrolling all the way to the top of the page has the scroll bar disappear behind the header and you must scroll down before it can be used. Tested with Firefox v68.

**Comment by thomasmitchell** [comment]
Fixed in 0c2e325b72ac4766a30f7a41e0d4280936e4e8f6

**Comment by thomasmitchell** [comment]
Released in 0.8.0
