### ISSUE TITLE
support specifying trusted ca cert for storage backends

### ISSUE THREAD

**Issue by thomasmitchell** [thomasmmitchell/doomsday#13]
Right now, the cert must either be trusted by the system or you have to skip ssl validation entirely. We can allow people to give specific CA certificates to trust.

**Comment by siennathesane** [comment]
Any more thoughts/progress on this one? It would be useful for cloud.gov.

**Comment by thomasmitchell** [comment]
Hoping to get it into the next minor.

**Comment by thomasmitchell** [comment]
d955d342838dc045884c9774950c3e31f730a6eb handles this for Vault. Still need to implement for credhub/opsman.

**Comment by thomasmitchell** [comment]
0c471697179779004580588c93b68824410405be does it for CredHub.

**Comment by thomasmitchell** [comment]
ce2f38bd4e0b811448b3633698e55481e437cb0d does it for Opsman
