### ISSUE TITLE
Interpolating credentials into config yml w/o storing in plaintext?

### ISSUE THREAD

**Issue by aegershman** [thomasmmitchell/doomsday#14]
Any thoughts on how credentials could be fed in to `doomsday` without storing them in plaintext like in `ddayconfig.yml`? E.g. retrieving them from a service binding to spring cloud config or the credhub or vault service broker?

Plaintext isn't the end of planet earth, since I could always encrypt creds in plaintext using [`sops`](https://github.com/mozilla/sops#using-the-publish-command) and decrypting it as part of a delivery pipeline, but am curious if anyone else an opinion on it or a way they like to do it.

Or maybe everybody just stores it in plaintext on their laptop 🤷‍♂ Just figured I'd ask

Feel free to close whenever. Thanks for your time 👍

**Comment by thomasmitchell** [comment]
Using `bosh interpolate` may be a good way to get credentials in from Credhub. Using https://github.com/geofffranks/spruce can be a good way to get credentials in from Vault.

Passing in the manifest as a pseudo-file from the output of one of those commands can prevent you from having to store the output on disk.

`doomsday server -m <(spruce merge ddayconfig-base.yml)`

**Comment by thomasmitchell** [comment]
The story for CF is a little less polished. I would suggest a script that builds the manifest like the above, pushes the app, and then gets rid of the filled out manifest.
