### ISSUE TITLE
no certificates are expiring soon page does not have a show all button

### ISSUE THREAD

**Issue by thomasmitchell** [thomasmmitchell/doomsday#19]
Arguably the page you would most want to show all on. That should be fixed...

**Comment by kitsirota** [comment]
+1 I was just looking for the show all button too.  We cleared up upcoming certs, but there were definitely certs coming up in the next 3 months that wont display now

**Comment by daviddob** [comment]
Initial implementation can be found on [this branch](/doomsday-project/doomsday/tree/fix-show-all) - tested and working.

**Comment by thomasmitchell** [comment]
fixed by #25
