### ISSUE TITLE
Bosh release

### ISSUE THREAD

**Issue by scottillogical** [thomasmmitchell/doomsday#9]
(please tell me if there is a better forum to ask) Any plans to package this as a bosh release?   If not, and its not objectionable we may look into doing this ourselves.

**Comment by thomasmitchell** [comment]
@daviddob has a pretty much finished boshrelease somewhere. Pretty much just waiting for me to cut this dang next doomsday release to make it public, so you can blame me.

soon™

**Comment by thomasmitchell** [comment]
🎊 boshrelease
https://github.com/doomsday-project/doomsday-boshrelease/releases

**Comment by scottillogical** [comment]
Got this deployed today! Pretty sweet thanks!  
![image](https://user-images.githubusercontent.com/130153/68708742-550bec00-0562-11ea-8dc0-901594d228e5.png)

**Comment by thomasmitchell** [comment]
Hope that it serves you well!
